// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxxwrrlvneupflclrkzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4eHdycmx2bmV1cGZsY2xya3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzkyMDIsImV4cCI6MjA2NzAxNTIwMn0.SBAKDHf96vZs5-HfOhEK2NVijj0PgUutbX_r-pkCTFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});